#!/bin/bash

source src/scripts/ccg/cl07_common

TABLE=$OUT/table7_oracle_kbest
K_ALG=1

mkdir -p $TABLE

cat /dev/null > $TABLE/log
cat /dev/null > $TABLE/results

echo "POS tagging development set" | tee -a $TABLE/log

$BIN/pos --model $POS --input $GOLD/wsj00.raw --output $TABLE/wsj00.pos 2>> $TABLE/log
$BIN/pos --model $POS --input $GOLD/wsj00.nofail.raw --output $TABLE/wsj00.nofail.pos 2>> $TABLE/log

echo

function run(){
  MODEL=$1
  DECODER=$2
  SUFFIX=$3
  KBEST=$4
  OTHER=$5

  WSJ00=wsj00
  GOLD_PREFIX=00.g.$DECODER.$KBEST.$MODEL
  AUTO_PREFIX=00.a.$DECODER.$KBEST.$MODEL
  if [[ $SUFFIX != "" ]]; then
    WSJ00=wsj00.$SUFFIX
    GOLD_PREFIX=00.g.$SUFFIX.$DECODER.$KBEST.$MODEL
    AUTO_PREFIX=00.a.$SUFFIX.$DECODER.$KBEST.$MODEL
  fi

  echo "parsing development set with $MODEL and k=$KBEST on gold POS" | tee -a $TABLE/log

  $BIN/parser --parser $WORK/$MODEL --super $SUPER --input $GOLD/$WSJ00.pos \
    --prefix $TABLE/$GOLD_PREFIX --decoder $DECODER --pos $POS \
    --printer deps --force_words false --parser-maxsupercats $MAXCATS \
    --betas $BETA --dict_cutoffs $CUTOFF --kbest $KBEST \
    --kbest_algorithm $K_ALG --super-forward_beam_ratio $FWDBEAM \
    $OTHER

  echo "evaluating development set" | tee -a $TABLE/log

  $SCRIPTS/evaluate_oracle $GOLD/$WSJ00.stagged $GOLD/$WSJ00.ccgbank_deps $TABLE/$GOLD_PREFIX.out $KBEST \
    > $TABLE/$GOLD_PREFIX.eval 2> $TABLE/$GOLD_PREFIX.eval.log

  echo "parsing development set with $MODEL and k=$KBEST on auto POS" | tee -a $TABLE/log

  $BIN/parser --parser $WORK/$MODEL --super $SUPER --input $TABLE/$WSJ00.pos \
    --prefix $TABLE/$AUTO_PREFIX --decoder $DECODER --pos $POS \
    --printer deps --force_words false  --parser-maxsupercats $MAXCATS \
    --betas $BETA --dict_cutoffs $CUTOFF --kbest $KBEST \
    --kbest_algorithm $K_ALG --super-forward_beam_ratio $FWDBEAM \
    $OTHER

  echo "evaluating development set" | tee -a $TABLE/log

  $SCRIPTS/evaluate_oracle $GOLD/$WSJ00.stagged $GOLD/$WSJ00.ccgbank_deps $TABLE/$AUTO_PREFIX.out $KBEST \
    > $TABLE/$AUTO_PREFIX.eval 2> $TABLE/$AUTO_PREFIX.eval.log

  LP=`grep '^lp:' $TABLE/$GOLD_PREFIX.eval | sed 's/^lp: *//; s/%.*//'`
  LR=`grep '^lr:' $TABLE/$GOLD_PREFIX.eval | sed 's/^lr: *//; s/%.*//'`
  LF=`grep '^lf:' $TABLE/$GOLD_PREFIX.eval | sed 's/^lf: *//; s/%.*//'`

  ALF=`grep '^lf:' $TABLE/$AUTO_PREFIX.eval | sed 's/^lf: *//; s/%.*//'`
  LSENT=`grep '^lsent:' $TABLE/$GOLD_PREFIX.eval | sed 's/^lsent: *//; s/%.*//'`

  UP=`grep '^up:' $TABLE/$GOLD_PREFIX.eval | sed 's/^up: *//; s/%.*//'`
  UR=`grep '^ur:' $TABLE/$GOLD_PREFIX.eval | sed 's/^ur: *//; s/%.*//'`
  UF=`grep '^uf:' $TABLE/$GOLD_PREFIX.eval | sed 's/^uf: *//; s/%.*//'`

  CATS=`grep '^cats:' $TABLE/$GOLD_PREFIX.eval | sed 's/^cats: *//; s/%.*//'`

  COVER=`grep '^cover:' $TABLE/$GOLD_PREFIX.eval | sed 's/^cover: *//; s/%.*//'`

  echo "$MODEL $LP $LR $LF $ALF $LSENT $UP $UR $UF $CATS $COVER suffix=$SUFFIX decoder=$DECODER k=$KBEST" | tee -a $TABLE/results
}

#run $DERIVS_REV derivs "" 10 ""
#run $DERIVS_REV derivs "" 50 ""
#run $HYBRID deps "" 10 ""
#run $HYBRID deps "" 50 ""
run $DERIVS_REV derivs_unique "" 10 ""
run $DERIVS_REV derivs_unique "" 50 ""
#run $DERIVS_REV derivs nofail 10 ""
#run $DERIVS_REV derivs nofail 50 ""
#run $HYBRID deps nofail 10 ""
#run $HYBRID deps nofail 50 ""
#run $DERIVS_REV derivs_unique nofail 10 ""
#run $DERIVS_REV derivs_unique nofail 50 ""
