#!/bin/bash

source src/scripts/ccg/cl07_common

TABLE=$OUT/table7_gold_auli_retrain

mkdir -p $TABLE

cat /dev/null > $TABLE/log
cat /dev/null > $TABLE/results

echo "POS tagging development set" | tee -a $TABLE/log

$BIN/pos --model $POS --input $GOLD/wsj00.raw --output $TABLE/wsj00.pos 2>> $TABLE/log
$BIN/pos --model $POS --input $GOLD/wsj00.nofail.raw --output $TABLE/wsj00.nofail.pos 2>> $TABLE/log

SUPER="/n/schwa01/data/jkk/auli_retrain/model_3400k"

echo

function run(){
  MODEL=$1
  DECODER=$2
  SUFFIX=$3
  BETAS=$4
  CUTOFFS=$5
  OTHER=$6

  WSJ00=wsj00
  AUTO_PREFIX=00.a.$BETAS.$CUTOFFS.$MODEL
  if [[ $SUFFIX != "" ]]; then
    WSJ00=wsj00.$SUFFIX
    AUTO_PREFIX=00.a.$SUFFIX.$BETAS.$CUTOFFS.$MODEL
  fi


  echo "parsing development set with $MODEL,betas=$BETAS,dict_cutoffs=$CUTOFFS on auto POS" | tee -a $TABLE/log

  $BIN/parser --parser $WORK/$MODEL --super $SUPER --input $TABLE/$WSJ00.pos \
    --prefix $TABLE/$AUTO_PREFIX --decoder $DECODER \
    --printer deps --force_words false --parser-maxsupercats $MAXCATS \
    --betas $BETAS --dict_cutoffs $CUTOFFS \
    --super-forward_beam_ratio $FWDBEAM --gold_deps $GOLD/$WSJ00.ccgbank_deps \
    --pos $POS $OTHER

  echo "evaluating development set" | tee -a $TABLE/log

  $SCRIPTS/evaluate $GOLD/$WSJ00.stagged $GOLD/$WSJ00.ccgbank_deps $TABLE/$AUTO_PREFIX.out \
    > $TABLE/$AUTO_PREFIX.eval 2> $TABLE/$AUTO_PREFIX.eval.log

  LP=`grep '^lp:' $TABLE/$AUTO_PREFIX.eval | sed 's/^lp: *//; s/%.*//'`
  LR=`grep '^lr:' $TABLE/$AUTO_PREFIX.eval | sed 's/^lr: *//; s/%.*//'`
  LF=`grep '^lf:' $TABLE/$AUTO_PREFIX.eval | sed 's/^lf: *//; s/%.*//'`

  LSENT=`grep '^lsent:' $TABLE/$AUTO_PREFIX.eval | sed 's/^lsent: *//; s/%.*//'`

  UP=`grep '^up:' $TABLE/$AUTO_PREFIX.eval | sed 's/^up: *//; s/%.*//'`
  UR=`grep '^ur:' $TABLE/$AUTO_PREFIX.eval | sed 's/^ur: *//; s/%.*//'`
  UF=`grep '^uf:' $TABLE/$AUTO_PREFIX.eval | sed 's/^uf: *//; s/%.*//'`

  CATS=`grep '^cats:' $TABLE/$AUTO_PREFIX.eval | sed 's/^cats: *//; s/%.*//'`

  COVER=`grep '^cover:' $TABLE/$AUTO_PREFIX.eval | sed 's/^cover: *//; s/%.*//'`

  echo "$MODEL $LP $LR $LF $LSENT $UP $UR $UF $CATS $COVER suffix=$SUFFIX betas=$BETAS dict_cutoffs=$CUTOFFS" | tee -a $TABLE/results
}

run $DERIVS_REV gold_deps "" 0.075 20 ""
run $DERIVS_REV gold_deps "" 0.03 20 ""
run $DERIVS_REV gold_deps "" 0.01 20 ""
run $DERIVS_REV gold_deps "" 0.005 20 ""
run $DERIVS_REV gold_deps "" 0.001 150 ""
run $DERIVS_REV gold_deps "" 0.01,0.005,0.001 20,20,150 ""
run $DERIVS_REV gold_deps "" $BETA $CUTOFF ""
#run $DERIVS_REV gold_deps nofail 0.075 20 ""
#run $DERIVS_REV gold_deps nofail 0.03 20 ""
#run $DERIVS_REV gold_deps nofail 0.01 20 ""
#run $DERIVS_REV gold_deps nofail 0.005 20 ""
#run $DERIVS_REV gold_deps nofail 0.001 150 ""
#run $DERIVS_REV gold_deps nofail 0.01,0.005,0.001 20,20,150 ""
run $DERIVS_REV gold_deps nofail $BETA $CUTOFF ""
