#!/usr/bin/env python

import sys

GRS = "grs"
CAT = "cat"

def die(msg):
  print >> sys.stderr, msg
  sys.exit()

def read_markedup(markedup):
  cats = {}
  mode = CAT
  cat = ""
  annotated = ""
  alt = ""
  ngrs = 0

  for line in markedup:
    line = line.strip()
    if not line:
      mode = CAT
      if alt:
        cats[" {0}".format(alt)] = " {0}".format(annotated)
      alt = annotated = ""
    elif not line.startswith("#") and not line.startswith("="):
      if mode == CAT:
        cat = line
        mode = GRS
      elif mode == GRS:
        line = line.split()
        if not annotated:
          annotated = line[1]
          ngrs = int(line[0])
        elif line[0].startswith("!"):
          alt = line[1]
  return cats



if __name__ == "__main__":
  if len(sys.argv) != 2:
    die("Usage: {0} <markedup file> < <parsed file>")
  cats = read_markedup(open(sys.argv[1], "rU"))
  for line in sys.stdin:
    for cat, repl in cats.items():
      line = line.replace(cat, repl)
    print line,
