#!/bin/bash

PROGRAM=`basename $0`

if [ ! $# == 1 ]; then
  (
    echo "$PROGRAM: incorrect number of command line arguments"
    echo "usage: $PROGRAM <work>"
    echo "where: <work> is where the data should be stored"
  ) > /dev/stderr;
    exit 1;
fi

WORK=$1

BIN=bin
SCRIPTS=src/scripts/ccg

POS=$WORK/pos_as_super_sigma_0.811
GOLD=$WORK/gold

echo "training POS as supertagger"

echo

mkdir -p $POS

$BIN/train_pos --model $POS --input $GOLD/wsj02-21.nopos.stagged --solver bfgs \
  --comment 'CCGbank sections 02-21' --niterations 500 --verbose --sigma 0.811 | \
  tee $POS/log
