package utcompling.scalalogic.discourse.candc.call.impl

import opennlp.scalabha.util.FileUtils
import org.junit.Test

class BoxerImplTests {

  @Test
  def test() {

    val b = new BoxerImpl()

    val everyManLovesAWoman =
      """% this file was generated by the following command(s):
%   /Users/dhg/workspace/candc/bin/candc --models /Users/dhg/workspace/candc/bin/../models/boxer --candc-printer boxer

:- op(601, xfx, (/)).
:- op(601, xfx, (\)).
:- multifile ccg/2, id/2.
:- discontiguous ccg/2, id/2.

ccg(1,
 rp(s:dcl,
  ba(s:dcl,
   fa(np:nb,
    t(np:nb/n, 'Every', 'every', 'DT', 'I-NP', 'O'),
    t(n, 'man', 'man', 'NN', 'I-NP', 'O')),
   fa(s:dcl\np,
    t((s:dcl\np)/np, 'loves', 'love', 'VBZ', 'I-VP', 'O'),
    fa(np:nb,
     t(np:nb/n, 'a', 'a', 'DT', 'I-NP', 'O'),
     t(n, 'woman', 'woman', 'NN', 'I-NP', 'O')))),
  t(period, '.', '.', '.', 'O', 'O'))).

id('0', [1]).

"""

    println(b.callBoxer(everyManLovesAWoman, Map()))

  }
}
